### ISSUE TITLE
Realse before Update please

### ISSUE THREAD

**Issue by sghazagh** [Miouyouyou/MyyQi#4]
Can you please release the old working as a branch before updating the new stuff in master?

As the "GetPatchAndCompileKernel.sh" scripts download the stuff at the time of building, that would be ideal to get the links and contents from the branch rather than master which updates continuously.

For instance, I am in the middle of build then realized that the master is updating and resources is not available any more.
So have to fetch the source again because resources is not available anymore ...
(/lib/module and .config file for instance)

MEantime, in README.md file, you still refering to rc1 but it's talking about rc2.
```
export KERNEL_BRANCH=v4.12-rc1
export KERNEL_VERSION=4.12.0-rc1
```

**Comment by Miouyouyou** [comment]
I hesitate between branching and just tagging here. Creating a branch for each RC might be a bit overkill, since the only use for the current version number is to get the appropriate kernel configuration file which could easily be fetched using the tag as reference, and I only bring modifications to the last release, essentially.

I'll correct the README, and actually I'll try to find a way to update it automatically using the script content.

**Comment by sghazagh** [comment]
Make sense, so this should be closed now.

**Comment by Miouyouyou** [comment]
The tagging system will be tested this week when releasing the next RC. I'll update this report when it's the case.
